apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user3-jenkins-pvc
  namespace: user3-jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeName: pv-user3-jenkins
