apiVersion: apps/v1
kind: Deployment
metadata:
  name: user3-was-deployment
  namespace: user3-was
  labels:
    app: user3-was
    owner: user3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user3-was
      owner: user3
  template:
    metadata:
      labels:
        app: user3-was
        owner: user3
    spec:
      containers:
        - name: user3-was-container
          image: hklee2748/spring-petclinic
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: user3-was-data
              mountPath: /logs
      volumes:
        - name: user3-was-data
          persistentVolumeClaim:
            claimName: user3-was-pvc
