apiVersion: v1
kind: Namespace
metadata:
  name: user3-jenkins
  labels: 
    owner: user3
    app: jenkins

---
apiVersion: v1
kind: Namespace
metadata:
  name: user3-was
  labels: 
    owner: user3
    app: was
